//André Luiz Gonçalves da Silva Teixeira
//RA: 2564289

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author andre
 */
import javax.swing.JOptionPane;

public class FormPrincipal extends javax.swing.JFrame {
   
    /**
     * Creates new form FormPrincipal
     */
    
    private FormPrincipal() {
        initComponents();
        setupListeners();
    }
    
    //Singleton
    private static FormPrincipal formPrincipal;
    public static FormPrincipal getFormPrincipal(){
        if(formPrincipal==null){
            formPrincipal = new FormPrincipal();
        }
        return formPrincipal;
    }
    
    private void setupListeners(){
        //Botão Sair
        if (btnSair != null) {
            btnSair.addActionListener(e -> {
                int resposta = JOptionPane.showConfirmDialog(
                    this, 
                    "Tem certeza que deseja sair do sistema?", 
                    "Confirmar Saída", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE
                );

                if (resposta == JOptionPane.YES_OPTION) {
                    dispose();
                }
            });

        }
        
        if (miCadGarment != null) {
            miCadGarment.addActionListener(e -> FormCadGarment.getFormCadGarment().setVisible(true)); //Reflexividade 
        }
        
        if (miRealizarVenda != null) {
            miRealizarVenda.addActionListener(e -> FormVenda.getFormVenda().setVisible(true)); //Reflexividade
        }
        if (miRelatorioGeral != null) {
            miRelatorioGeral.addActionListener(e -> FormRelatorio.getFormRelatorio().setVisible(true)); //Reflexividade
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mbPrincipal = new javax.swing.JMenuBar();
        mnCadastro = new javax.swing.JMenu();
        miCadGarment = new javax.swing.JMenuItem();
        miRealizarVenda = new javax.swing.JMenuItem();
        mnRelatorio = new javax.swing.JMenu();
        miRelatorioGeral = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro e Venda de Roupas");

        mnCadastro.setText("Operações");

        miCadGarment.setText("Gerenciar Peças de Roupa");
        mnCadastro.add(miCadGarment);

        miRealizarVenda.setText("Realizar Venda");
        mnCadastro.add(miRealizarVenda);

        mbPrincipal.add(mnCadastro);

        mnRelatorio.setText("Relatórios");

        miRelatorioGeral.setText("Relatório Geral de Peças");
        mnRelatorio.add(miRelatorioGeral);

        mbPrincipal.add(mnRelatorio);

        setJMenuBar(mbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btnSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(100, 100, 100)
                .addComponent(btnSair)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar mbPrincipal;
    private javax.swing.JMenuItem miCadGarment;
    private javax.swing.JMenuItem miRealizarVenda;
    private javax.swing.JMenuItem miRelatorioGeral;
    private javax.swing.JMenu mnCadastro;
    private javax.swing.JMenu mnRelatorio;
    // End of variables declaration//GEN-END:variables
}
